### ISSUE TITLE
No reaction on touch in android dropdown menu

### ISSUE THREAD

**Issue by thohug** [datamapio/posmo_one_testing#5] opened 2020-06-22 09:28 UTC
**Setting**
Zurich, Switzerland, Android

geofence: 1
do_not_track: 0
wifi_over_gps: 1
data_over_wifi_only: 0

**Issue**

No reaction on touch in status bar (probably should open app/app settings?).

![grafik](https://user-images.githubusercontent.com/67195528/85271545-39af7a80-b47b-11ea-802e-91136ec6a071.png)

**Comment by Fangio92** [comment] 2020-06-22 12:38
It is like that by design

**Comment by Fangio92** [comment] 2020-06-22 13:57
From version 279, click on notification will open app/settings. If you find any problem with the app, please let me know.

**Comment by djr4** [comment] 2020-06-22 19:26
@thohug please close this issue when you confirm this addition.

**Closed as completed** 2020-06-23 06:06 UTC
Labels: enhancement
